### ISSUE TITLE
unable to launch the project

### ISSUE THREAD

**Issue by survivant** [TravisBumgarner/todotoday#47]
I git a git clone and read the readme.  but when I enter the command ``npm run fill-it``, I obtain those errors.
````
PS C:\test\todotoday> npm run fill-it

> todotoday@1.0.0 fill-it C:\test\todotoday
> npm i && npm i --prefix frontend && npm i --prefix backend

audited 128 packages in 0.614s

15 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "todotoday" under a package
npm ERR! also called "todotoday". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sd003526\AppData\Roaming\npm-cache\_logs\2022-07-18T12_44_22_242Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! todotoday@1.0.0 fill-it: `npm i && npm i --prefix frontend && npm i --prefix backend`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the todotoday@1.0.0 fill-it script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sd003526\AppData\Roaming\npm-cache\_logs\2022-07-18T12_44_22_277Z-debug.log
PS C:\test\todotoday>
````

the logs file
````
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '--prefix',
1 verbose cli   'frontend'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v12.22.12
4 verbose npm-session bd4b99ace28bd898
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly pacote directory manifest for undefined@file: fetched in 11ms
8 timing stage:loadCurrentTree Completed in 23ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
12 silly install loadShrinkwrap
13 warn read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 380ms
15 silly install loadAllDepsIntoIdealTree
16 timing stage:rollbackFailedOptional Completed in 0ms
17 timing stage:runTopLevelLifecycles Completed in 404ms
18 verbose stack Error: Refusing to install package with name "todotoday" under a package
18 verbose stack also called "todotoday". Did you name your project the same
18 verbose stack as the dependency you're installing?
18 verbose stack
18 verbose stack For more information, see:
18 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
18 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:75:14)
18 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
18 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
18 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
18 verbose stack     at hasMinimumFields (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:30:12)
18 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
18 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
18 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
18 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
18 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
18 verbose stack     at Array.forEach (<anonymous>)
18 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
18 verbose stack     at Array.forEach (<anonymous>)
18 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
18 verbose stack     at module.exports (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:3)
18 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose cwd C:\test\todotoday
20 verbose Windows_NT 10.0.19043
21 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--prefix" "frontend"
22 verbose node v12.22.12
23 verbose npm  v6.14.16
24 error code ENOSELF
25 error Refusing to install package with name "todotoday" under a package
25 error also called "todotoday". Did you name your project the same
25 error as the dependency you're installing?
25 error
25 error For more information, see:
25 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
26 verbose exit [ 1, true ]

````

**Comment by TravisBumgarner** [comment]
Hey - Unfortunately at this point I have no way to do dev work on Windows machines and haven't in years so I'm not sure how to resolve. :/
